//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadPayerPlanDataToMongo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveRequest", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.model")]
    [System.SerializableAttribute()]
    public partial class ReceiveRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ArchiveMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CertificateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeleteMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MessageUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SizeLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.State StateFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ArchiveMessage {
            get {
                return this.ArchiveMessageField;
            }
            set {
                if ((this.ArchiveMessageField.Equals(value) != true)) {
                    this.ArchiveMessageField = value;
                    this.RaisePropertyChanged("ArchiveMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationType {
            get {
                return this.AuthenticationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTypeField, value) != true)) {
                    this.AuthenticationTypeField = value;
                    this.RaisePropertyChanged("AuthenticationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Certificate {
            get {
                return this.CertificateField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateField, value) != true)) {
                    this.CertificateField = value;
                    this.RaisePropertyChanged("Certificate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DeleteMessage {
            get {
                return this.DeleteMessageField;
            }
            set {
                if ((this.DeleteMessageField.Equals(value) != true)) {
                    this.DeleteMessageField = value;
                    this.RaisePropertyChanged("DeleteMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MessageUid {
            get {
                return this.MessageUidField;
            }
            set {
                if ((this.MessageUidField.Equals(value) != true)) {
                    this.MessageUidField = value;
                    this.RaisePropertyChanged("MessageUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SizeLimit {
            get {
                return this.SizeLimitField;
            }
            set {
                if ((this.SizeLimitField.Equals(value) != true)) {
                    this.SizeLimitField = value;
                    this.RaisePropertyChanged("SizeLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.State StateFlag {
            get {
                return this.StateFlagField;
            }
            set {
                if ((this.StateFlagField.Equals(value) != true)) {
                    this.StateFlagField = value;
                    this.RaisePropertyChanged("StateFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    public enum State : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Received = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDNReceived = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageSummary", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.model")]
    [System.SerializableAttribute()]
    public partial class MessageSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MessageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MessageUidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MessageSize {
            get {
                return this.MessageSizeField;
            }
            set {
                if ((this.MessageSizeField.Equals(value) != true)) {
                    this.MessageSizeField = value;
                    this.RaisePropertyChanged("MessageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MessageUid {
            get {
                return this.MessageUidField;
            }
            set {
                if ((this.MessageUidField.Equals(value) != true)) {
                    this.MessageUidField = value;
                    this.RaisePropertyChanged("MessageUid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesHeader", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    [System.SerializableAttribute()]
    public partial class SesHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] CcAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateComposedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.Importance ImportanceFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] ReplyToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress ReturnPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecureSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.Sensitivity SensitivityFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.State StateFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] ToAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] CcAddress {
            get {
                return this.CcAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CcAddressField, value) != true)) {
                    this.CcAddressField = value;
                    this.RaisePropertyChanged("CcAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateComposed {
            get {
                return this.DateComposedField;
            }
            set {
                if ((this.DateComposedField.Equals(value) != true)) {
                    this.DateComposedField = value;
                    this.RaisePropertyChanged("DateComposed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateReceived {
            get {
                return this.DateReceivedField;
            }
            set {
                if ((this.DateReceivedField.Equals(value) != true)) {
                    this.DateReceivedField = value;
                    this.RaisePropertyChanged("DateReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSent {
            get {
                return this.DateSentField;
            }
            set {
                if ((this.DateSentField.Equals(value) != true)) {
                    this.DateSentField = value;
                    this.RaisePropertyChanged("DateSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.Importance ImportanceFlag {
            get {
                return this.ImportanceFlagField;
            }
            set {
                if ((this.ImportanceFlagField.Equals(value) != true)) {
                    this.ImportanceFlagField = value;
                    this.RaisePropertyChanged("ImportanceFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMDN {
            get {
                return this.IsMDNField;
            }
            set {
                if ((this.IsMDNField.Equals(value) != true)) {
                    this.IsMDNField = value;
                    this.RaisePropertyChanged("IsMDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicSubject {
            get {
                return this.PublicSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicSubjectField, value) != true)) {
                    this.PublicSubjectField = value;
                    this.RaisePropertyChanged("PublicSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] ReplyTo {
            get {
                return this.ReplyToField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplyToField, value) != true)) {
                    this.ReplyToField = value;
                    this.RaisePropertyChanged("ReplyTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress ReturnPath {
            get {
                return this.ReturnPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnPathField, value) != true)) {
                    this.ReturnPathField = value;
                    this.RaisePropertyChanged("ReturnPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecureSubject {
            get {
                return this.SecureSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SecureSubjectField, value) != true)) {
                    this.SecureSubjectField = value;
                    this.RaisePropertyChanged("SecureSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.Sensitivity SensitivityFlag {
            get {
                return this.SensitivityFlagField;
            }
            set {
                if ((this.SensitivityFlagField.Equals(value) != true)) {
                    this.SensitivityFlagField = value;
                    this.RaisePropertyChanged("SensitivityFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.State StateFlag {
            get {
                return this.StateFlagField;
            }
            set {
                if ((this.StateFlagField.Equals(value) != true)) {
                    this.StateFlagField = value;
                    this.RaisePropertyChanged("StateFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] ToAddress {
            get {
                return this.ToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressField, value) != true)) {
                    this.ToAddressField = value;
                    this.RaisePropertyChanged("ToAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesAddress", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    [System.SerializableAttribute()]
    public partial class SesAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Importance", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    public enum Importance : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Highest = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lowest = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sensitivity", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    public enum Sensitivity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Personal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confidential = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHeaderListRequest", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.model")]
    [System.SerializableAttribute()]
    public partial class MessageHeaderListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] MessageUidsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] MessageUids {
            get {
                return this.MessageUidsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageUidsField, value) != true)) {
                    this.MessageUidsField = value;
                    this.RaisePropertyChanged("MessageUids");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesMessage", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    [System.SerializableAttribute()]
    public partial class SesMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAttachment[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyHTMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] CcAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateComposedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.Importance ImportanceFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEncryptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SESMessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecureSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.Sensitivity SensitivityFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.State StateFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] ToAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAttachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyHTML {
            get {
                return this.BodyHTMLField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyHTMLField, value) != true)) {
                    this.BodyHTMLField = value;
                    this.RaisePropertyChanged("BodyHTML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyText {
            get {
                return this.BodyTextField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyTextField, value) != true)) {
                    this.BodyTextField = value;
                    this.RaisePropertyChanged("BodyText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] CcAddress {
            get {
                return this.CcAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CcAddressField, value) != true)) {
                    this.CcAddressField = value;
                    this.RaisePropertyChanged("CcAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateComposed {
            get {
                return this.DateComposedField;
            }
            set {
                if ((this.DateComposedField.Equals(value) != true)) {
                    this.DateComposedField = value;
                    this.RaisePropertyChanged("DateComposed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateReceived {
            get {
                return this.DateReceivedField;
            }
            set {
                if ((this.DateReceivedField.Equals(value) != true)) {
                    this.DateReceivedField = value;
                    this.RaisePropertyChanged("DateReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSent {
            get {
                return this.DateSentField;
            }
            set {
                if ((this.DateSentField.Equals(value) != true)) {
                    this.DateSentField = value;
                    this.RaisePropertyChanged("DateSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.Importance ImportanceFlag {
            get {
                return this.ImportanceFlagField;
            }
            set {
                if ((this.ImportanceFlagField.Equals(value) != true)) {
                    this.ImportanceFlagField = value;
                    this.RaisePropertyChanged("ImportanceFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEncrypted {
            get {
                return this.IsEncryptedField;
            }
            set {
                if ((this.IsEncryptedField.Equals(value) != true)) {
                    this.IsEncryptedField = value;
                    this.RaisePropertyChanged("IsEncrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMDN {
            get {
                return this.IsMDNField;
            }
            set {
                if ((this.IsMDNField.Equals(value) != true)) {
                    this.IsMDNField = value;
                    this.RaisePropertyChanged("IsMDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSigned {
            get {
                return this.IsSignedField;
            }
            set {
                if ((this.IsSignedField.Equals(value) != true)) {
                    this.IsSignedField = value;
                    this.RaisePropertyChanged("IsSigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicSubject {
            get {
                return this.PublicSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicSubjectField, value) != true)) {
                    this.PublicSubjectField = value;
                    this.RaisePropertyChanged("PublicSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SESMessageId {
            get {
                return this.SESMessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SESMessageIdField, value) != true)) {
                    this.SESMessageIdField = value;
                    this.RaisePropertyChanged("SESMessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecureSubject {
            get {
                return this.SecureSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SecureSubjectField, value) != true)) {
                    this.SecureSubjectField = value;
                    this.RaisePropertyChanged("SecureSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.Sensitivity SensitivityFlag {
            get {
                return this.SensitivityFlagField;
            }
            set {
                if ((this.SensitivityFlagField.Equals(value) != true)) {
                    this.SensitivityFlagField = value;
                    this.RaisePropertyChanged("SensitivityFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.State StateFlag {
            get {
                return this.StateFlagField;
            }
            set {
                if ((this.StateFlagField.Equals(value) != true)) {
                    this.StateFlagField = value;
                    this.RaisePropertyChanged("StateFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadPayerPlanDataToMongo.ServiceReference1.SesAddress[] ToAddress {
            get {
                return this.ToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressField, value) != true)) {
                    this.ToAddressField = value;
                    this.RaisePropertyChanged("ToAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesAttachment", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    [System.SerializableAttribute()]
    public partial class SesAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispositionType", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.Model")]
    public enum DispositionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dispatched = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Displayed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesMessageStatus", Namespace="http://schemas.datacontract.org/2004/07/Ses.Core.model")]
    [System.SerializableAttribute()]
    public partial class SesMessageStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MdnConfirmationDteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MdnConfirmationDte {
            get {
                return this.MdnConfirmationDteField;
            }
            set {
                if ((object.ReferenceEquals(this.MdnConfirmationDteField, value) != true)) {
                    this.MdnConfirmationDteField = value;
                    this.RaisePropertyChanged("MdnConfirmationDte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageStatus {
            get {
                return this.MessageStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageStatusField, value) != true)) {
                    this.MessageStatusField = value;
                    this.RaisePropertyChanged("MessageStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fromAddress {
            get {
                return this.fromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.fromAddressField, value) != true)) {
                    this.fromAddressField = value;
                    this.RaisePropertyChanged("fromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string toAddress {
            get {
                return this.toAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.toAddressField, value) != true)) {
                    this.toAddressField = value;
                    this.RaisePropertyChanged("toAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", ConfigurationName="ServiceReference1.SecureIntegrationServiceImap")]
    public interface SecureIntegrationServiceImap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageNumber", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageNumberResponse")]
        int GetMessageNumber(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageNumber", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageNumberResponse")]
        System.Threading.Tasks.Task<int> GetMessageNumberAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetReadMessageNumber", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetReadMessageNumberResponse")]
        int GetReadMessageNumber(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetReadMessageNumber", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetReadMessageNumberResponse")]
        System.Threading.Tasks.Task<int> GetReadMessageNumberAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageList", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageListResponse")]
        LoadPayerPlanDataToMongo.ServiceReference1.MessageSummary[] GetMessageList(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageList", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageListResponse")]
        System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.MessageSummary[]> GetMessageListAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeader", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeaderResponse")]
        LoadPayerPlanDataToMongo.ServiceReference1.SesHeader GetMessageHeader(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeader", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeaderResponse")]
        System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.SesHeader> GetMessageHeaderAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeaderList", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeaderListResponse")]
        System.Collections.Generic.Dictionary<long, LoadPayerPlanDataToMongo.ServiceReference1.SesHeader> GetMessageHeaderList(LoadPayerPlanDataToMongo.ServiceReference1.MessageHeaderListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeaderList", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageHeaderListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<long, LoadPayerPlanDataToMongo.ServiceReference1.SesHeader>> GetMessageHeaderListAsync(LoadPayerPlanDataToMongo.ServiceReference1.MessageHeaderListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessage", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageResponse")]
        LoadPayerPlanDataToMongo.ServiceReference1.SesMessage GetMessage(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessage", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetMessageResponse")]
        System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.SesMessage> GetMessageAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMessage", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMessageResponse")]
        string SendMessage(LoadPayerPlanDataToMongo.ServiceReference1.SesMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMessage", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMessageResponse")]
        System.Threading.Tasks.Task<string> SendMessageAsync(LoadPayerPlanDataToMongo.ServiceReference1.SesMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/DeleteMessage", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/DeleteMessageResponse")]
        bool DeleteMessage(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/DeleteMessage", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/DeleteMessageResponse")]
        System.Threading.Tasks.Task<bool> DeleteMessageAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/UpdateMessageStatus", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/UpdateMessageStatusResponse")]
        bool UpdateMessageStatus(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/UpdateMessageStatus", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/UpdateMessageStatusResponse")]
        System.Threading.Tasks.Task<bool> UpdateMessageStatusAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMDN", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMDNResponse")]
        string SendMDN(string ReturnAddress, string FromAddress, string MessageId, string Text, LoadPayerPlanDataToMongo.ServiceReference1.DispositionType disposition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMDN", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SendMDNResponse")]
        System.Threading.Tasks.Task<string> SendMDNAsync(string ReturnAddress, string FromAddress, string MessageId, string Text, LoadPayerPlanDataToMongo.ServiceReference1.DispositionType disposition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SentMessageStatus", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SentMessageStatusResponse")]
        LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus[] SentMessageStatus(LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SentMessageStatus", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/SentMessageStatusResponse")]
        System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus[]> SentMessageStatusAsync(LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageNumber", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageNumberResponse")]
        int GetUnseenMessageNumber(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageNumber", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageNumberResponse")]
        System.Threading.Tasks.Task<int> GetUnseenMessageNumberAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageList", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageListResponse")]
        long[] GetUnseenMessageList(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageList", ReplyAction="http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureInt" +
            "egrationServiceImap/GetUnseenMessageListResponse")]
        System.Threading.Tasks.Task<long[]> GetUnseenMessageListAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecureIntegrationServiceImapChannel : LoadPayerPlanDataToMongo.ServiceReference1.SecureIntegrationServiceImap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecureIntegrationServiceImapClient : System.ServiceModel.ClientBase<LoadPayerPlanDataToMongo.ServiceReference1.SecureIntegrationServiceImap>, LoadPayerPlanDataToMongo.ServiceReference1.SecureIntegrationServiceImap {
        
        public SecureIntegrationServiceImapClient() {
        }
        
        public SecureIntegrationServiceImapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecureIntegrationServiceImapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureIntegrationServiceImapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureIntegrationServiceImapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetMessageNumber(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessageNumber(request);
        }
        
        public System.Threading.Tasks.Task<int> GetMessageNumberAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessageNumberAsync(request);
        }
        
        public int GetReadMessageNumber(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetReadMessageNumber(request);
        }
        
        public System.Threading.Tasks.Task<int> GetReadMessageNumberAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetReadMessageNumberAsync(request);
        }
        
        public LoadPayerPlanDataToMongo.ServiceReference1.MessageSummary[] GetMessageList(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessageList(request);
        }
        
        public System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.MessageSummary[]> GetMessageListAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessageListAsync(request);
        }
        
        public LoadPayerPlanDataToMongo.ServiceReference1.SesHeader GetMessageHeader(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessageHeader(request);
        }
        
        public System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.SesHeader> GetMessageHeaderAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessageHeaderAsync(request);
        }
        
        public System.Collections.Generic.Dictionary<long, LoadPayerPlanDataToMongo.ServiceReference1.SesHeader> GetMessageHeaderList(LoadPayerPlanDataToMongo.ServiceReference1.MessageHeaderListRequest request) {
            return base.Channel.GetMessageHeaderList(request);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<long, LoadPayerPlanDataToMongo.ServiceReference1.SesHeader>> GetMessageHeaderListAsync(LoadPayerPlanDataToMongo.ServiceReference1.MessageHeaderListRequest request) {
            return base.Channel.GetMessageHeaderListAsync(request);
        }
        
        public LoadPayerPlanDataToMongo.ServiceReference1.SesMessage GetMessage(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.SesMessage> GetMessageAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetMessageAsync(request);
        }
        
        public string SendMessage(LoadPayerPlanDataToMongo.ServiceReference1.SesMessage message) {
            return base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task<string> SendMessageAsync(LoadPayerPlanDataToMongo.ServiceReference1.SesMessage message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public bool DeleteMessage(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.DeleteMessage(request);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMessageAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.DeleteMessageAsync(request);
        }
        
        public bool UpdateMessageStatus(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.UpdateMessageStatus(request);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMessageStatusAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.UpdateMessageStatusAsync(request);
        }
        
        public string SendMDN(string ReturnAddress, string FromAddress, string MessageId, string Text, LoadPayerPlanDataToMongo.ServiceReference1.DispositionType disposition) {
            return base.Channel.SendMDN(ReturnAddress, FromAddress, MessageId, Text, disposition);
        }
        
        public System.Threading.Tasks.Task<string> SendMDNAsync(string ReturnAddress, string FromAddress, string MessageId, string Text, LoadPayerPlanDataToMongo.ServiceReference1.DispositionType disposition) {
            return base.Channel.SendMDNAsync(ReturnAddress, FromAddress, MessageId, Text, disposition);
        }
        
        public LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus[] SentMessageStatus(LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus request) {
            return base.Channel.SentMessageStatus(request);
        }
        
        public System.Threading.Tasks.Task<LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus[]> SentMessageStatusAsync(LoadPayerPlanDataToMongo.ServiceReference1.SesMessageStatus request) {
            return base.Channel.SentMessageStatusAsync(request);
        }
        
        public int GetUnseenMessageNumber(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetUnseenMessageNumber(request);
        }
        
        public System.Threading.Tasks.Task<int> GetUnseenMessageNumberAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetUnseenMessageNumberAsync(request);
        }
        
        public long[] GetUnseenMessageList(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetUnseenMessageList(request);
        }
        
        public System.Threading.Tasks.Task<long[]> GetUnseenMessageListAsync(LoadPayerPlanDataToMongo.ServiceReference1.ReceiveRequest request) {
            return base.Channel.GetUnseenMessageListAsync(request);
        }
    }
}
